package contracts

import (
	"context"
	"time"
)

// This file freezes the authentication-flow contract of F1 (plan v2, F1;
// ADR-SEC-01 for custody, ADR-0001 for identity).
//
// AuthFlow performs ONE grant: an interactive OAuth grant (PKCE or device_code)
// or a refresh. It is stateful only for the duration of the flow. The
// single-flight invariant of Refresh is enforced by CredentialStore.RefreshLock,
// NOT by the family: see the invariant comment on Refresh below.

// AuthChallenge is what an AuthFlow returns to the caller so the user (or the
// GUI) can complete the grant. The same struct carries both PKCE and
// device_code fields because a caller reads only the fields its mode populates,
// and Mode disambiguates.
type AuthChallenge struct {
	// Mode is the AuthMode this challenge belongs to.
	Mode AuthMode
	// State is the anti-CSRF/replay token for PKCE: at least 128 bits,
	// single-use, generated by the flow, and bound to the challenge. Empty for
	// device_code, whose correlation is the device_code itself.
	State string

	// --- device_code fields ---

	// DeviceCode is the opaque code polled at Poll.
	DeviceCode string
	// UserCode is the short code the user types at VerificationURI.
	UserCode string
	// VerificationURI is where the user authorises the device.
	VerificationURI string
	// Interval is the minimum poll interval the provider demands. Poll must not
	// be called faster than this.
	Interval time.Duration
	// ExpiresAt bounds the whole device grant.
	ExpiresAt time.Time

	// --- pkce fields ---

	// PKCEVerifier is the code verifier (kept server-side; never sent to the
	// browser). It is a Secret so it cannot leak through a log.
	PKCEVerifier Secret
	// CodeChallenge is the S256 challenge.
	CodeChallenge string
	// RedirectURI is the exact callback URI used for this exchange.
	RedirectURI string
}

// RefreshToken is rotation-aware. Providers differ on whether a refresh returns
// a new refresh token; keeping it as a typed, Secret-carrying value makes the
// rotation explicit and never-loggable.
type RefreshToken struct {
	// Token is the refresh token value. Empty means "none supplied".
	Token Secret
	// Rotated is true when Token is a NEW refresh token that must replace the
	// stored one. False means the previous token remains valid.
	Rotated bool
	// Scopes are the scopes associated with this token, when the provider
	// reports them.
	Scopes []string
}

// AuthResult is the output of a completed grant or refresh. It carries the
// access material ALREADY intended for sealing: the caller passes Access (and
// Token, when rotated) through SecretStore.Seal before persisting. Plaintext
// never goes into Credential directly.
type AuthResult struct {
	// Access is the access token to be sealed.
	Access Secret
	// Token is the refresh token to be sealed, when the grant produced one.
	Token RefreshToken
	// ExpiresAt is when Access expires.
	ExpiresAt time.Time
	// Scopes granted by the provider (may be narrower than requested).
	Scopes []string
	// Account is the non-secret identity learned during the grant.
	Account AccountMeta
	// AuthMode records which mechanism produced this result.
	AuthMode AuthMode
}

// AuthFlow performs one grant. A ProviderFamily builds it (F1.2); the concrete
// flows live in internal/auth/*.
type AuthFlow interface {
	// Kind reports which mechanism this flow implements.
	Kind() AuthMode
	// Begin starts the grant and returns the challenge the user must act on.
	// For device_code this is the authorization request; for PKCE it is the
	// authorization URL plus the state to verify on return.
	Begin(ctx context.Context, desc ProviderDescriptor) (AuthChallenge, error)
	// Poll advances a device_code grant. For PKCE, Poll completes the exchange
	// once the caller supplies the code back. It respects Interval and ExpiresAt
	// and returns auth.oauth_flow_expired when the challenge times out.
	Poll(ctx context.Context, ch AuthChallenge) (AuthResult, error)
	// Refresh exchanges a refresh token for fresh access material.
	//
	// INVARIANT — single-flight per CredentialID: Refresh is NOT
	// concurrency-safe on its own, and the ProviderFamily does not serialize it.
	// The caller MUST hold CredentialStore.RefreshLock(cred.ID) for the whole
	// Refresh call, so N concurrent callers produce exactly one upstream
	// exchange and the rest observe its result. On an invalid/revoked token the
	// flow returns auth.credential_invalid (ScopeCredential, not retryable); on
	// a transient failure it returns auth.refresh_failed (retryable). A
	// successful refresh MUST be sealed and persisted before the lock is
	// released, otherwise the next caller refreshes again.
	Refresh(ctx context.Context, cred Credential, token RefreshToken) (AuthResult, error)
}
